# Generated by Django 3.2.5 on 2021-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='telegram',
            field=models.CharField(blank=True, help_text='Введите свой ID. Если вы не знаете свой ID, вам понадобится связаться с ботом @my_id_bot. Напишите ему "/start" и в ответном сообщении вы должны получить свой уникальный номер идентификации.', max_length=20, null=True, verbose_name='Телеграмм ID'),
        ),
    ]
