# Generated by Django 3.2.5 on 2021-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='photo',
            field=models.ImageField(default='users/avatar5.png', upload_to='users/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
