# Generated by Django 3.2.5 on 2021-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('repair', 'Специалист по ремонту'), ('service', 'Специалист по обслуживанию'), ('consultant', 'Консультант'), ('user', 'Пользователь без доступа в CRM')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
