# Generated by Django 3.2.5 on 2021-07-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210725_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='photo',
        ),
    ]
